pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }
    options {
        ansiColor('exterm')
    }
    parameters {
        choice(name:'action', choices:['apply','destroy'], description:'pick something')
    }

    stages {
        stage('Init') {
            steps {
                sh """
                    cd 02-sg
                    terraform init -reconfigure
                """
            }
        }
        stage('Plan') {
            steps {
                sh """
                    cd 02-sg
                    terraform plan -out=tfplan
                    terraform apply "tfplan"
                """
            }
        }
        stage('Apply') {
           when {
              expression {
                    params.action == 'Apply'
              }
           }
           steps {
              sh """
                cd 02-sg
                terraform apply -auto-approve
              """
           }
        }
        stage('Destroy') {
            when {
                expression {
                    params.action == 'Destroy'
                }
            }
            steps {
                sh """
                    cd 02-sg
                    terraform destroy tfplan
                    terraform destroy -auto-approve
                """
            }
        }
    }

    post {
        always {
            echo 'I will always say hello'
        }
    }
}